builds:
- binary: srv-account
  main: ./cmd/srv/account.go
  goos:
#  - windows
  - darwin
  - linux
  - freebsd
  goarch:
  - amd64
  - 386
  - arm
  - arm64
  goarm:
  - 6
  - 7
#- binary: srv-user
#  main: ./cmd/srv/user.go
#  goos:
#  - windows
#  - darwin
#  - linux
#  - freebsd
#  goarch:
#  - amd64
#  - 386
#  - arm
#  - arm64
#  goarm:
#  - 6
#  - 7
#archive:
#  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#  replacements:
#    darwin: Darwin
#    linux: Linux
#    windows: Windows
#    386: i386
#    amd64: x86_64
#  format_overrides:
#  - goos: windows
#    format: zip