// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/user/proto/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 用户基本信息
type UserBase struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Iphone               string   `protobuf:"bytes,3,opt,name=iphone,proto3" json:"iphone,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Sex                  int32    `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBase) Reset()         { *m = UserBase{} }
func (m *UserBase) String() string { return proto.CompactTextString(m) }
func (*UserBase) ProtoMessage()    {}
func (*UserBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d1605ffe4478dcda, []int{0}
}
func (m *UserBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBase.Unmarshal(m, b)
}
func (m *UserBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBase.Marshal(b, m, deterministic)
}
func (dst *UserBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBase.Merge(dst, src)
}
func (m *UserBase) XXX_Size() int {
	return xxx_messageInfo_UserBase.Size(m)
}
func (m *UserBase) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBase.DiscardUnknown(m)
}

var xxx_messageInfo_UserBase proto.InternalMessageInfo

func (m *UserBase) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserBase) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserBase) GetIphone() string {
	if m != nil {
		return m.Iphone
	}
	return ""
}

func (m *UserBase) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserBase) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

type UserId struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d1605ffe4478dcda, []int{1}
}
func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (dst *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(dst, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserAllOption struct {
	Sex                  int32    `protobuf:"varint,1,opt,name=sex,proto3" json:"sex,omitempty"`
	Page                 *Page    `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAllOption) Reset()         { *m = UserAllOption{} }
func (m *UserAllOption) String() string { return proto.CompactTextString(m) }
func (*UserAllOption) ProtoMessage()    {}
func (*UserAllOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d1605ffe4478dcda, []int{2}
}
func (m *UserAllOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAllOption.Unmarshal(m, b)
}
func (m *UserAllOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAllOption.Marshal(b, m, deterministic)
}
func (dst *UserAllOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAllOption.Merge(dst, src)
}
func (m *UserAllOption) XXX_Size() int {
	return xxx_messageInfo_UserAllOption.Size(m)
}
func (m *UserAllOption) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAllOption.DiscardUnknown(m)
}

var xxx_messageInfo_UserAllOption proto.InternalMessageInfo

func (m *UserAllOption) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserAllOption) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *UserAllOption) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserAll struct {
	All                  []*UserBase `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	Page                 *Page       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserAll) Reset()         { *m = UserAll{} }
func (m *UserAll) String() string { return proto.CompactTextString(m) }
func (*UserAll) ProtoMessage()    {}
func (*UserAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d1605ffe4478dcda, []int{3}
}
func (m *UserAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAll.Unmarshal(m, b)
}
func (m *UserAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAll.Marshal(b, m, deterministic)
}
func (dst *UserAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAll.Merge(dst, src)
}
func (m *UserAll) XXX_Size() int {
	return xxx_messageInfo_UserAll.Size(m)
}
func (m *UserAll) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAll.DiscardUnknown(m)
}

var xxx_messageInfo_UserAll proto.InternalMessageInfo

func (m *UserAll) GetAll() []*UserBase {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *UserAll) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

// 空消息
type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d1605ffe4478dcda, []int{4}
}
func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (dst *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(dst, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

// 分页
type Page struct {
	PageIndex            int64    `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageTotal            int64    `protobuf:"varint,3,opt,name=page_total,json=pageTotal,proto3" json:"page_total,omitempty"`
	Count                int64    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Total                int64    `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d1605ffe4478dcda, []int{5}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (dst *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(dst, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *Page) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Page) GetPageTotal() int64 {
	if m != nil {
		return m.PageTotal
	}
	return 0
}

func (m *Page) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Page) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*UserBase)(nil), "user.UserBase")
	proto.RegisterType((*UserId)(nil), "user.UserId")
	proto.RegisterType((*UserAllOption)(nil), "user.UserAllOption")
	proto.RegisterType((*UserAll)(nil), "user.UserAll")
	proto.RegisterType((*Null)(nil), "user.Null")
	proto.RegisterType((*Page)(nil), "user.Page")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// 用户
	UserAdd(ctx context.Context, in *UserBase, opts ...grpc.CallOption) (*UserBase, error)
	UserUpdate(ctx context.Context, in *UserBase, opts ...grpc.CallOption) (*UserBase, error)
	UserDelete(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserId, error)
	UserQueryOne(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserBase, error)
	UserQueryAll(ctx context.Context, in *UserAllOption, opts ...grpc.CallOption) (*UserAll, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UserAdd(ctx context.Context, in *UserBase, opts ...grpc.CallOption) (*UserBase, error) {
	out := new(UserBase)
	err := c.cc.Invoke(ctx, "/user.UserService/UserAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserUpdate(ctx context.Context, in *UserBase, opts ...grpc.CallOption) (*UserBase, error) {
	out := new(UserBase)
	err := c.cc.Invoke(ctx, "/user.UserService/UserUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserDelete(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserId, error) {
	out := new(UserId)
	err := c.cc.Invoke(ctx, "/user.UserService/UserDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserQueryOne(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserBase, error) {
	out := new(UserBase)
	err := c.cc.Invoke(ctx, "/user.UserService/UserQueryOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserQueryAll(ctx context.Context, in *UserAllOption, opts ...grpc.CallOption) (*UserAll, error) {
	out := new(UserAll)
	err := c.cc.Invoke(ctx, "/user.UserService/UserQueryAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// 用户
	UserAdd(context.Context, *UserBase) (*UserBase, error)
	UserUpdate(context.Context, *UserBase) (*UserBase, error)
	UserDelete(context.Context, *UserId) (*UserId, error)
	UserQueryOne(context.Context, *UserId) (*UserBase, error)
	UserQueryAll(context.Context, *UserAllOption) (*UserAll, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_UserAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserAdd(ctx, req.(*UserBase))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserUpdate(ctx, req.(*UserBase))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserDelete(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserQueryOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserQueryOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserQueryOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserQueryOne(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserQueryAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAllOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserQueryAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserQueryAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserQueryAll(ctx, req.(*UserAllOption))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserAdd",
			Handler:    _UserService_UserAdd_Handler,
		},
		{
			MethodName: "UserUpdate",
			Handler:    _UserService_UserUpdate_Handler,
		},
		{
			MethodName: "UserDelete",
			Handler:    _UserService_UserDelete_Handler,
		},
		{
			MethodName: "UserQueryOne",
			Handler:    _UserService_UserQueryOne_Handler,
		},
		{
			MethodName: "UserQueryAll",
			Handler:    _UserService_UserQueryAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srv/user/proto/user.proto",
}

func init() { proto.RegisterFile("srv/user/proto/user.proto", fileDescriptor_user_d1605ffe4478dcda) }

var fileDescriptor_user_d1605ffe4478dcda = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x5f, 0x6b, 0xd4, 0x40,
	0x10, 0xef, 0xde, 0x26, 0xf1, 0x6e, 0xae, 0x2d, 0xb2, 0x8a, 0xc4, 0x88, 0x12, 0xf6, 0x29, 0x28,
	0x5c, 0xe1, 0xf4, 0x0b, 0x28, 0xbe, 0x1c, 0x42, 0xab, 0xa9, 0x7d, 0xb5, 0xac, 0xdd, 0xe1, 0x5c,
	0xd8, 0x26, 0x21, 0x9b, 0x54, 0x2d, 0xf8, 0x11, 0xfc, 0xc6, 0x3e, 0xc8, 0xec, 0xe6, 0x7a, 0x26,
	0x3e, 0xe8, 0xdb, 0xfc, 0xfe, 0xcc, 0xec, 0x6f, 0x26, 0x81, 0xc7, 0xae, 0xbd, 0x39, 0xe9, 0x1d,
	0xb6, 0x27, 0x4d, 0x5b, 0x77, 0xb5, 0x2f, 0x57, 0xbe, 0x14, 0x11, 0xd5, 0xf2, 0x07, 0xcc, 0x2f,
	0x1c, 0xb6, 0x6f, 0x94, 0x43, 0x71, 0x0c, 0x33, 0xa3, 0x53, 0x96, 0xb3, 0x82, 0x97, 0x33, 0xa3,
	0xc5, 0x13, 0x58, 0x90, 0xe7, 0xb2, 0x52, 0xd7, 0x98, 0xce, 0x72, 0x56, 0x2c, 0xca, 0x39, 0x11,
	0xa7, 0xea, 0x1a, 0xc5, 0x23, 0x48, 0x4c, 0xf3, 0xa5, 0xae, 0x30, 0xe5, 0x5e, 0x19, 0x90, 0xc8,
	0x60, 0xde, 0x28, 0xe7, 0xbe, 0xd6, 0xad, 0x4e, 0xa3, 0xd0, 0xb3, 0xc3, 0xe2, 0x3e, 0x70, 0x87,
	0xdf, 0xd2, 0x38, 0x67, 0x45, 0x5c, 0x52, 0x29, 0x53, 0x48, 0xe8, 0xf9, 0x8d, 0x9e, 0x3e, 0x2e,
	0x3f, 0xc1, 0x11, 0x29, 0xaf, 0xad, 0x3d, 0x6b, 0x3a, 0x53, 0x57, 0xbb, 0x66, 0x76, 0xd7, 0x2c,
	0x9e, 0x41, 0xd4, 0xa8, 0x6d, 0x88, 0xb6, 0x5c, 0xc3, 0xca, 0x2f, 0xf7, 0x5e, 0x6d, 0xb1, 0xf4,
	0xfc, 0x38, 0x3f, 0x1f, 0xe7, 0x97, 0xef, 0xe0, 0xde, 0x30, 0x5f, 0xe4, 0xc0, 0x95, 0xb5, 0x29,
	0xcb, 0x79, 0xb1, 0x5c, 0x1f, 0x87, 0x31, 0xbb, 0xa3, 0x94, 0x24, 0xfd, 0xeb, 0x25, 0x99, 0x40,
	0x74, 0xda, 0x5b, 0x2b, 0x7f, 0x32, 0x88, 0x88, 0x16, 0x4f, 0x01, 0x48, 0xb8, 0x34, 0x95, 0x1e,
	0x32, 0xf3, 0x72, 0x41, 0xcc, 0x86, 0x08, 0x4a, 0xe6, 0x65, 0x67, 0x6e, 0xc3, 0x50, 0x4e, 0x57,
	0xda, 0xe2, 0xb9, 0xb9, 0xdd, 0xf7, 0x76, 0x75, 0xa7, 0xac, 0xcf, 0x3d, 0xf4, 0x7e, 0x24, 0x42,
	0x3c, 0x84, 0xf8, 0xaa, 0xee, 0xab, 0xce, 0x5f, 0x97, 0x97, 0x01, 0x10, 0x1b, 0xfc, 0x71, 0x60,
	0x3d, 0x58, 0xff, 0x62, 0xb0, 0xa4, 0x4d, 0xce, 0xb1, 0xbd, 0x31, 0x57, 0x28, 0x5e, 0x0c, 0x4b,
	0x6b, 0x2d, 0x26, 0x7b, 0x66, 0x13, 0x2c, 0x0f, 0xc4, 0x0a, 0x80, 0xd0, 0x45, 0xa3, 0x55, 0x87,
	0xff, 0xe1, 0x7f, 0x1e, 0xfc, 0x6f, 0xd1, 0x62, 0x87, 0xe2, 0x70, 0xaf, 0x6f, 0x74, 0x36, 0x42,
	0x7e, 0xf6, 0x21, 0xd5, 0x1f, 0x7a, 0x6c, 0xbf, 0x9f, 0x55, 0x53, 0xf7, 0xdf, 0xb3, 0x5f, 0xfd,
	0xe1, 0xa7, 0x4f, 0xf6, 0x60, 0xef, 0xb8, 0xfb, 0x43, 0xb2, 0xa3, 0x11, 0x29, 0x0f, 0x3e, 0x27,
	0xfe, 0x4f, 0x7f, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x84, 0x25, 0x6d, 0xb1, 0x06, 0x03, 0x00,
	0x00,
}
