// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/account/proto/account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 账户级别
type AccountBase_Level int32

const (
	AccountBase_LevelDefault AccountBase_Level = 0
	AccountBase_LevelOne     AccountBase_Level = 1
	AccountBase_LevelTwo     AccountBase_Level = 2
	AccountBase_LevelThree   AccountBase_Level = 3
)

var AccountBase_Level_name = map[int32]string{
	0: "LevelDefault",
	1: "LevelOne",
	2: "LevelTwo",
	3: "LevelThree",
}
var AccountBase_Level_value = map[string]int32{
	"LevelDefault": 0,
	"LevelOne":     1,
	"LevelTwo":     2,
	"LevelThree":   3,
}

func (x AccountBase_Level) String() string {
	return proto.EnumName(AccountBase_Level_name, int32(x))
}
func (AccountBase_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_6ce6c7a23784eeef, []int{0, 0}
}

// 账户状态
type AccountBase_Status int32

const (
	AccountBase_StatusDefault AccountBase_Status = 0
	// 正常
	AccountBase_StatusNormal AccountBase_Status = 1
	// 冻结
	AccountBase_StatusFrozen AccountBase_Status = 2
)

var AccountBase_Status_name = map[int32]string{
	0: "StatusDefault",
	1: "StatusNormal",
	2: "StatusFrozen",
}
var AccountBase_Status_value = map[string]int32{
	"StatusDefault": 0,
	"StatusNormal":  1,
	"StatusFrozen":  2,
}

func (x AccountBase_Status) String() string {
	return proto.EnumName(AccountBase_Status_name, int32(x))
}
func (AccountBase_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_6ce6c7a23784eeef, []int{0, 1}
}

// 账户基本信息
type AccountBase struct {
	// @inject_tag: db:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id"`
	// @inject_tag: db:"user_id" valid:"required~用户id必须存在"
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" db:"user_id" valid:"required~用户id必须存在"`
	// @inject_tag: db:"account_level" valid:"required~账户级别必须存在"
	AccountLevel AccountBase_Level `protobuf:"varint,3,opt,name=account_level,json=accountLevel,proto3,enum=account.AccountBase_Level" json:"account_level,omitempty" db:"account_level" valid:"required~账户级别必须存在"`
	// @inject_tag: db:"balance"
	Balance float32 `protobuf:"fixed32,4,opt,name=balance,proto3" json:"balance,omitempty" db:"balance"`
	// @inject_tag: db:"account_status" valid:"required~账户状态必须存在"
	AccountStatus        AccountBase_Status `protobuf:"varint,5,opt,name=account_status,json=accountStatus,proto3,enum=account.AccountBase_Status" json:"account_status,omitempty" db:"account_status" valid:"required~账户状态必须存在"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountBase) Reset()         { *m = AccountBase{} }
func (m *AccountBase) String() string { return proto.CompactTextString(m) }
func (*AccountBase) ProtoMessage()    {}
func (*AccountBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_6ce6c7a23784eeef, []int{0}
}
func (m *AccountBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBase.Unmarshal(m, b)
}
func (m *AccountBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBase.Marshal(b, m, deterministic)
}
func (dst *AccountBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBase.Merge(dst, src)
}
func (m *AccountBase) XXX_Size() int {
	return xxx_messageInfo_AccountBase.Size(m)
}
func (m *AccountBase) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBase.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBase proto.InternalMessageInfo

func (m *AccountBase) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AccountBase) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AccountBase) GetAccountLevel() AccountBase_Level {
	if m != nil {
		return m.AccountLevel
	}
	return AccountBase_LevelDefault
}

func (m *AccountBase) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *AccountBase) GetAccountStatus() AccountBase_Status {
	if m != nil {
		return m.AccountStatus
	}
	return AccountBase_StatusDefault
}

// 账户Id
type AccountId struct {
	// 账户id
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountId) Reset()         { *m = AccountId{} }
func (m *AccountId) String() string { return proto.CompactTextString(m) }
func (*AccountId) ProtoMessage()    {}
func (*AccountId) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_6ce6c7a23784eeef, []int{1}
}
func (m *AccountId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountId.Unmarshal(m, b)
}
func (m *AccountId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountId.Marshal(b, m, deterministic)
}
func (dst *AccountId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountId.Merge(dst, src)
}
func (m *AccountId) XXX_Size() int {
	return xxx_messageInfo_AccountId.Size(m)
}
func (m *AccountId) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountId.DiscardUnknown(m)
}

var xxx_messageInfo_AccountId proto.InternalMessageInfo

func (m *AccountId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 账户更新请求
type AccountUpdateReq struct {
	// 账户id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 账户余额
	Balance              float32  `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountUpdateReq) Reset()         { *m = AccountUpdateReq{} }
func (m *AccountUpdateReq) String() string { return proto.CompactTextString(m) }
func (*AccountUpdateReq) ProtoMessage()    {}
func (*AccountUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_6ce6c7a23784eeef, []int{2}
}
func (m *AccountUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountUpdateReq.Unmarshal(m, b)
}
func (m *AccountUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountUpdateReq.Marshal(b, m, deterministic)
}
func (dst *AccountUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountUpdateReq.Merge(dst, src)
}
func (m *AccountUpdateReq) XXX_Size() int {
	return xxx_messageInfo_AccountUpdateReq.Size(m)
}
func (m *AccountUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountUpdateReq proto.InternalMessageInfo

func (m *AccountUpdateReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AccountUpdateReq) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// 账户全部
type AccountAll struct {
	// 账户信息
	All []*AccountBase `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	// 页数
	Page                 *Page    `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountAll) Reset()         { *m = AccountAll{} }
func (m *AccountAll) String() string { return proto.CompactTextString(m) }
func (*AccountAll) ProtoMessage()    {}
func (*AccountAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_6ce6c7a23784eeef, []int{3}
}
func (m *AccountAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAll.Unmarshal(m, b)
}
func (m *AccountAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAll.Marshal(b, m, deterministic)
}
func (dst *AccountAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAll.Merge(dst, src)
}
func (m *AccountAll) XXX_Size() int {
	return xxx_messageInfo_AccountAll.Size(m)
}
func (m *AccountAll) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAll.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAll proto.InternalMessageInfo

func (m *AccountAll) GetAll() []*AccountBase {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *AccountAll) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

// 空消息
type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_6ce6c7a23784eeef, []int{4}
}
func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (dst *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(dst, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

// 分页
type Page struct {
	// 页
	PageIndex int64 `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	// 每页大小
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 总页数
	PageTotal int64 `protobuf:"varint,3,opt,name=page_total,json=pageTotal,proto3" json:"page_total,omitempty"`
	// 条数
	Count int64 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// 总条数
	Total                int64    `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_6ce6c7a23784eeef, []int{5}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (dst *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(dst, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *Page) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Page) GetPageTotal() int64 {
	if m != nil {
		return m.PageTotal
	}
	return 0
}

func (m *Page) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Page) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountBase)(nil), "account.AccountBase")
	proto.RegisterType((*AccountId)(nil), "account.AccountId")
	proto.RegisterType((*AccountUpdateReq)(nil), "account.AccountUpdateReq")
	proto.RegisterType((*AccountAll)(nil), "account.AccountAll")
	proto.RegisterType((*Null)(nil), "account.Null")
	proto.RegisterType((*Page)(nil), "account.Page")
	proto.RegisterEnum("account.AccountBase_Level", AccountBase_Level_name, AccountBase_Level_value)
	proto.RegisterEnum("account.AccountBase_Status", AccountBase_Status_name, AccountBase_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	// 账户添加
	AccountAdd(ctx context.Context, in *AccountBase, opts ...grpc.CallOption) (*AccountBase, error)
	// 账户更新
	AccountUpdate(ctx context.Context, in *AccountUpdateReq, opts ...grpc.CallOption) (*empty.Empty, error)
	// 账户查询一个
	AccountQueryOne(ctx context.Context, in *AccountId, opts ...grpc.CallOption) (*AccountBase, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) AccountAdd(ctx context.Context, in *AccountBase, opts ...grpc.CallOption) (*AccountBase, error) {
	out := new(AccountBase)
	err := c.cc.Invoke(ctx, "/account.AccountService/AccountAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AccountUpdate(ctx context.Context, in *AccountUpdateReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.AccountService/AccountUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AccountQueryOne(ctx context.Context, in *AccountId, opts ...grpc.CallOption) (*AccountBase, error) {
	out := new(AccountBase)
	err := c.cc.Invoke(ctx, "/account.AccountService/AccountQueryOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	// 账户添加
	AccountAdd(context.Context, *AccountBase) (*AccountBase, error)
	// 账户更新
	AccountUpdate(context.Context, *AccountUpdateReq) (*empty.Empty, error)
	// 账户查询一个
	AccountQueryOne(context.Context, *AccountId) (*AccountBase, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_AccountAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountBase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/AccountAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountAdd(ctx, req.(*AccountBase))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AccountUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/AccountUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountUpdate(ctx, req.(*AccountUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AccountQueryOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountQueryOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/AccountQueryOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountQueryOne(ctx, req.(*AccountId))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountAdd",
			Handler:    _AccountService_AccountAdd_Handler,
		},
		{
			MethodName: "AccountUpdate",
			Handler:    _AccountService_AccountUpdate_Handler,
		},
		{
			MethodName: "AccountQueryOne",
			Handler:    _AccountService_AccountQueryOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srv/account/proto/account.proto",
}

func init() {
	proto.RegisterFile("srv/account/proto/account.proto", fileDescriptor_account_6ce6c7a23784eeef)
}

var fileDescriptor_account_6ce6c7a23784eeef = []byte{
	// 835 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcf, 0x8f, 0xdb, 0x44,
	0x14, 0xae, 0xed, 0xdd, 0x6c, 0xf6, 0xe5, 0xc7, 0xba, 0xd3, 0x0a, 0x19, 0xaf, 0x56, 0x1b, 0x2c,
	0xb1, 0x8a, 0xa2, 0xc6, 0xce, 0xa6, 0x48, 0xab, 0xe4, 0xc2, 0x3a, 0xa2, 0x48, 0x51, 0x69, 0xb7,
	0x78, 0xbb, 0x02, 0x21, 0xa4, 0x68, 0x12, 0x4f, 0x1d, 0x83, 0x63, 0x1b, 0x7b, 0xbc, 0x6d, 0x16,
	0x21, 0xf1, 0xe3, 0x52, 0x21, 0x21, 0xa1, 0xd0, 0x4b, 0x0f, 0x3d, 0xc0, 0x01, 0x90, 0x90, 0x38,
	0x20, 0x04, 0x12, 0x12, 0x7f, 0x03, 0x87, 0xfe, 0x0b, 0x25, 0xa5, 0xff, 0x05, 0xf2, 0x8c, 0x93,
	0x6c, 0xda, 0x20, 0x4e, 0x9e, 0xef, 0x7b, 0xdf, 0xfb, 0xde, 0xcc, 0x7b, 0x33, 0x86, 0xdd, 0x38,
	0x3a, 0x35, 0xf0, 0x60, 0x10, 0x24, 0x3e, 0x35, 0xc2, 0x28, 0xa0, 0xc1, 0x0c, 0xe9, 0x0c, 0xa1,
	0x8d, 0x0c, 0xaa, 0x7b, 0xe1, 0x87, 0x4e, 0xa6, 0x70, 0x82, 0xc0, 0xf1, 0x88, 0x81, 0x43, 0xd7,
	0xc0, 0xbe, 0x1f, 0x50, 0x4c, 0xdd, 0xc0, 0x8f, 0x79, 0x82, 0xba, 0x9d, 0x45, 0x19, 0xea, 0x27,
	0x77, 0x0c, 0x32, 0x0a, 0xe9, 0x38, 0x0b, 0x5e, 0x61, 0x9f, 0x41, 0xdd, 0x21, 0x7e, 0x3d, 0xbe,
	0x8b, 0x1d, 0x87, 0x44, 0x46, 0x10, 0xb2, 0xf4, 0x17, 0xad, 0xb4, 0x9f, 0x25, 0x28, 0x98, 0xbc,
	0x7c, 0x07, 0xc7, 0x04, 0xed, 0x80, 0xe8, 0xda, 0x8a, 0x50, 0x11, 0xaa, 0x52, 0xa7, 0x34, 0x31,
	0xa1, 0x96, 0xff, 0xe7, 0xd7, 0xef, 0xa7, 0xf7, 0x7f, 0x77, 0x6d, 0x4b, 0x74, 0x6d, 0xb4, 0x07,
	0x1b, 0x49, 0x4c, 0xa2, 0x9e, 0x6b, 0x2b, 0xe2, 0x39, 0xcd, 0xd3, 0x07, 0x3f, 0x72, 0x4d, 0x2e,
	0x8d, 0x76, 0x6d, 0x64, 0x41, 0x29, 0x3b, 0x54, 0xcf, 0x23, 0xa7, 0xc4, 0x53, 0xa4, 0x8a, 0x50,
	0x2d, 0x37, 0x55, 0x7d, 0x76, 0xf2, 0x73, 0x35, 0xf5, 0xb7, 0x52, 0x45, 0xe7, 0xe2, 0xc4, 0x2c,
	0xd7, 0x8a, 0xbc, 0xda, 0xd3, 0x3f, 0x7e, 0xf8, 0xfb, 0xfe, 0x4f, 0x56, 0x31, 0x53, 0x33, 0x01,
	0x7a, 0x15, 0x36, 0xfa, 0xd8, 0xc3, 0xfe, 0x80, 0x28, 0x6b, 0x15, 0xa1, 0x2a, 0x76, 0x0a, 0x13,
	0x33, 0x5f, 0xcb, 0x3d, 0xf9, 0xf3, 0xe1, 0xb3, 0xef, 0x1e, 0x59, 0xb3, 0x18, 0x3a, 0x81, 0xf2,
	0xac, 0x74, 0x4c, 0x31, 0x4d, 0x62, 0x65, 0x9d, 0xd5, 0xde, 0x5e, 0x59, 0xfb, 0x98, 0x49, 0x96,
	0x8b, 0x7f, 0xf9, 0xdb, 0xf4, 0xd3, 0xcf, 0xac, 0xd9, 0x01, 0xb8, 0x42, 0xbb, 0x06, 0xeb, 0x7c,
	0x1b, 0x32, 0x14, 0xd9, 0xe2, 0x0d, 0x72, 0x07, 0x27, 0x1e, 0x95, 0x2f, 0xa0, 0x22, 0xe4, 0x19,
	0x73, 0xe4, 0x13, 0x59, 0x98, 0xa3, 0xdb, 0x77, 0x03, 0x59, 0x44, 0x65, 0x00, 0x8e, 0x86, 0x11,
	0x21, 0xb2, 0xa4, 0xbd, 0x0e, 0x39, 0x6e, 0x88, 0x2e, 0x42, 0x89, 0xaf, 0x16, 0x46, 0x32, 0x14,
	0x39, 0x75, 0x33, 0x88, 0x46, 0xd8, 0x93, 0x85, 0x05, 0xf3, 0x66, 0x14, 0x9c, 0x11, 0x5f, 0x16,
	0xb5, 0x2b, 0xb0, 0x99, 0xed, 0xbf, 0x6b, 0xa3, 0xdd, 0x73, 0xd3, 0xda, 0x9a, 0x98, 0xc5, 0xc5,
	0xb4, 0x0e, 0x85, 0x74, 0x5e, 0xda, 0x0d, 0x90, 0x33, 0xf5, 0x49, 0x68, 0x63, 0x4a, 0x2c, 0xf2,
	0xd1, 0xff, 0x26, 0x21, 0x65, 0xd1, 0xe8, 0x74, 0xc8, 0xe2, 0xbc, 0xb7, 0xda, 0x3b, 0x00, 0x99,
	0x9d, 0xe9, 0x79, 0x68, 0x0f, 0x24, 0xec, 0x79, 0x8a, 0x50, 0x91, 0xaa, 0x85, 0xe6, 0xe5, 0x55,
	0xed, 0xb5, 0x52, 0x01, 0x7a, 0x05, 0xd6, 0x42, 0xec, 0x70, 0xb3, 0x42, 0xb3, 0x34, 0x17, 0xde,
	0xc2, 0x0e, 0xb1, 0x58, 0x48, 0xcb, 0xc1, 0xda, 0xcd, 0xc4, 0xf3, 0xb4, 0xaf, 0x04, 0x58, 0x4b,
	0x69, 0xb4, 0x03, 0x90, 0x06, 0x7a, 0xae, 0x6f, 0x93, 0x7b, 0x7c, 0xb3, 0xd6, 0x66, 0xca, 0x74,
	0x53, 0x02, 0x6d, 0x03, 0x03, 0xbd, 0xd8, 0x3d, 0xe3, 0xbe, 0x92, 0x95, 0x4f, 0x89, 0x63, 0xf7,
	0x6c, 0x91, 0x4b, 0x03, 0x8a, 0xf9, 0xcd, 0xcb, 0x72, 0x6f, 0xa7, 0x04, 0xba, 0x0c, 0xeb, 0xac,
	0x3e, 0xbb, 0x45, 0x92, 0xc5, 0x41, 0xca, 0x72, 0xfd, 0x3a, 0x67, 0x19, 0x68, 0x3e, 0x10, 0xa1,
	0x9c, 0x9d, 0xe7, 0x98, 0x44, 0xa7, 0xee, 0x80, 0xa0, 0x1b, 0x8b, 0x1e, 0xd8, 0x36, 0x5a, 0x79,
	0x6c, 0x75, 0x25, 0xab, 0x5d, 0xfa, 0xfc, 0xf1, 0x93, 0x6f, 0xc4, 0x92, 0x96, 0x9f, 0xbd, 0xff,
	0xb6, 0x50, 0x43, 0xef, 0x43, 0x69, 0x69, 0x42, 0xe8, 0xe5, 0xe7, 0x73, 0xe7, 0x93, 0x53, 0x5f,
	0xd2, 0xf9, 0xc3, 0xd7, 0x67, 0x0f, 0x5f, 0xbf, 0x96, 0x3e, 0x7c, 0x4d, 0x61, 0xc6, 0x48, 0x2d,
	0xcd, 0x7f, 0x33, 0x1f, 0xbb, 0xf6, 0x27, 0xa9, 0xfb, 0x09, 0x6c, 0x65, 0x2e, 0x6f, 0x27, 0x24,
	0x1a, 0x1f, 0xf9, 0x04, 0xa1, 0xe7, 0xfd, 0xbb, 0xf6, 0x7f, 0xec, 0x37, 0xb3, 0x45, 0xcb, 0xb6,
	0x7d, 0xa1, 0xd6, 0x79, 0x2c, 0x4c, 0xcc, 0xbf, 0x04, 0x74, 0x04, 0x39, 0x7e, 0x75, 0xb4, 0x43,
	0x80, 0x7b, 0x2e, 0x0e, 0x46, 0xc4, 0x77, 0x0e, 0x5a, 0x68, 0x67, 0x48, 0x69, 0x18, 0xb7, 0x0d,
	0xc3, 0x71, 0xe9, 0x30, 0xe9, 0xeb, 0x83, 0x60, 0x64, 0x2c, 0xc2, 0xea, 0xa5, 0xf4, 0xcb, 0xd7,
	0x87, 0x63, 0x82, 0x87, 0xba, 0x4f, 0x68, 0x53, 0xda, 0xd7, 0x1b, 0x6a, 0x79, 0xbf, 0x79, 0xa0,
	0x37, 0xf4, 0x86, 0xbe, 0xdf, 0x6e, 0xb5, 0x5a, 0x07, 0x35, 0x41, 0x68, 0xca, 0x38, 0x0c, 0x3d,
	0x77, 0xc0, 0x7e, 0x5a, 0xc6, 0x07, 0x71, 0xe0, 0xb7, 0x5f, 0x60, 0x2c, 0x04, 0xd2, 0x6b, 0x8d,
	0xab, 0xa8, 0x00, 0x9b, 0xd3, 0x5f, 0xbe, 0x9d, 0x3e, 0xfa, 0xe2, 0xd9, 0xc3, 0xaf, 0xdf, 0xdb,
	0x85, 0x1d, 0x00, 0x33, 0x74, 0xaf, 0x93, 0xb1, 0x99, 0xd0, 0x21, 0xda, 0xca, 0x8b, 0xea, 0xe6,
	0xbb, 0x75, 0xf3, 0x56, 0xb7, 0x7e, 0x9d, 0x8c, 0x2b, 0x62, 0x5f, 0x86, 0xf2, 0x92, 0xe0, 0x42,
	0x3f, 0xc7, 0xda, 0x7a, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x7e, 0x54, 0xdf, 0xb1,
	0x05, 0x00, 0x00,
}
